export * as NovelXGrowth from "./novelx-growth"

import { Schema } from "effect"

const Label = Schema.String.check(Schema.isMinLength(1), Schema.isMaxLength(120))
const Count = Schema.Int.check(Schema.isGreaterThanOrEqualTo(1), Schema.isLessThanOrEqualTo(500))
const Index = Schema.Int.check(Schema.isGreaterThanOrEqualTo(0))
const Sha256 = Schema.String.check(Schema.isPattern(/^[a-f0-9]{64}$/))

export const WorldLayerProfile = Schema.Struct({
  label: Label.annotate({
    description: "User-facing world layer, such as geography, nations, star systems, or institutions",
  }),
  parentLayerIndex: Schema.NullOr(Index).annotate({
    description: "Zero-based parent layer index, or null for a root layer; parents must appear before children",
  }),
  slotCount: Count.annotate({ description: "Number of empty planned slots to register for this layer" }),
})
export interface WorldLayerProfile extends Schema.Schema.Type<typeof WorldLayerProfile> {}

export const CharacterGroupProfile = Schema.Struct({
  label: Label.annotate({ description: "Functional character group, not a generated character name" }),
  slotCount: Count.annotate({ description: "Number of empty planned character slots in this group" }),
})
export interface CharacterGroupProfile extends Schema.Schema.Type<typeof CharacterGroupProfile> {}

export const Profile = Schema.Struct({
  title: Label.annotate({ description: "Short user-facing name for this Growth skeleton" }),
  genre: Schema.Struct({
    family: Label.annotate({ description: "Broad genre family selected after internal self-inquiry" }),
    label: Label.annotate({ description: "Specific user-facing genre description" }),
    scale: Label.annotate({ description: "World scale, such as a city, continent, planet, galaxy, or multiverse" }),
  }),
  worldLayers: Schema.Array(WorldLayerProfile).check(Schema.isMinLength(1), Schema.isMaxLength(20)),
  characterGroups: Schema.Array(CharacterGroupProfile).check(Schema.isMinLength(1), Schema.isMaxLength(20)),
  graphViews: Schema.Array(Label).check(Schema.isMinLength(1), Schema.isMaxLength(20)).annotate({
    description: "Empty graph views to register; these are query lenses, never invented fact nodes or relations",
  }),
  chapterCount: Count.annotate({
    description: "Number of standard empty chapters; titles and IDs are generated by the Harness",
  }),
})
export interface Profile extends Schema.Schema.Type<typeof Profile> {}

export const PlannedSlot = Schema.Struct({
  id: Schema.String,
  label: Label,
  ordinal: Count,
  status: Schema.Literal("planned"),
})
export interface PlannedSlot extends Schema.Schema.Type<typeof PlannedSlot> {}

export const PlannedWorldLayer = Schema.Struct({
  id: Schema.String,
  label: Label,
  ordinal: Count,
  parentId: Schema.NullOr(Schema.String),
  status: Schema.Literal("planned"),
  slots: Schema.Array(PlannedSlot),
})
export interface PlannedWorldLayer extends Schema.Schema.Type<typeof PlannedWorldLayer> {}

export const PlannedCharacterGroup = Schema.Struct({
  id: Schema.String,
  label: Label,
  ordinal: Count,
  status: Schema.Literal("planned"),
  slots: Schema.Array(PlannedSlot),
})
export interface PlannedCharacterGroup extends Schema.Schema.Type<typeof PlannedCharacterGroup> {}

export const PlannedGraphView = Schema.Struct({
  id: Schema.String,
  label: Label,
  ordinal: Count,
  status: Schema.Literal("planned"),
})
export interface PlannedGraphView extends Schema.Schema.Type<typeof PlannedGraphView> {}

export const PlannedChapter = Schema.Struct({
  id: Schema.String,
  label: Label,
  ordinal: Count,
  status: Schema.Literal("planned"),
  contentState: Schema.Literal("empty"),
})
export interface PlannedChapter extends Schema.Schema.Type<typeof PlannedChapter> {}

export const PlannedFile = Schema.Struct({
  id: Schema.String,
  label: Label,
  path: Schema.String,
  kind: Schema.Literals(["document", "view", "image"]),
  sourceId: Schema.String,
  status: Schema.Literal("planned"),
})
export interface PlannedFile extends Schema.Schema.Type<typeof PlannedFile> {}

export const PlannedPackageSection = Schema.Struct({
  id: Schema.String,
  label: Label,
  ordinal: Count,
  status: Schema.Literal("planned"),
})
export interface PlannedPackageSection extends Schema.Schema.Type<typeof PlannedPackageSection> {}

export const Manifest = Schema.Struct({
  schemaVersion: Schema.Literal(1),
  status: Schema.Literal("planned"),
  registeredAt: Schema.Int.check(Schema.isGreaterThanOrEqualTo(0)),
  source: Schema.Struct({
    sessionId: Schema.String,
    messageId: Schema.String,
    toolCallId: Schema.NullOr(Schema.String),
    profileSha256: Sha256,
  }),
  profile: Profile,
  surfaces: Schema.Struct({
    files: Schema.Struct({ items: Schema.Array(PlannedFile) }),
    world: Schema.Struct({ layers: Schema.Array(PlannedWorldLayer) }),
    characters: Schema.Struct({ groups: Schema.Array(PlannedCharacterGroup) }),
    graph: Schema.Struct({ views: Schema.Array(PlannedGraphView) }),
    story: Schema.Struct({
      id: Schema.String,
      label: Label,
      status: Schema.Literal("planned"),
      chapters: Schema.Array(PlannedChapter),
    }),
    package: Schema.Struct({
      id: Schema.String,
      label: Label,
      status: Schema.Literal("planned"),
      sections: Schema.Array(PlannedPackageSection),
    }),
  }),
  integritySha256: Sha256,
})
export interface Manifest extends Schema.Schema.Type<typeof Manifest> {}

export const MANIFEST_PATH = ".novelx/growth/skeleton.json"
