import { NovelXGrowth } from "@opencode-ai/schema"

export const fantasyTerrain = {
  title: "埃兰世界",
  genre: { family: "fantasy", label: "经典中土大世界魔幻", scale: "主大陆及周边海域" },
  designSummary: "一块由北方高山脊柱、中央低地与南部暖海共同塑造的主大陆，东西海岸形成清晰边界。",
  nodes: [
    terrain(
      "埃兰大陆",
      "continent",
      null,
      "core",
      "占据世界中央的主大陆，北高南低，山脉与河谷共同切分内部区域。",
      "古老陆块经多次抬升与侵蚀形成，承担整张地图的空间母体。",
      12,
      10,
      72,
      78,
    ),
    terrain(
      "西陲苍海",
      "ocean",
      null,
      "major",
      "包围大陆西侧的深水海域，海岸线曲折并散布外海岛链。",
      "大陆边缘快速沉降形成深水洋盆，为西岸提供明确外部边界。",
      0,
      12,
      18,
      72,
    ),
    terrain(
      "南境暖海",
      "sea",
      null,
      "major",
      "贴近大陆南缘的温暖内海，与主要河口和沿岸浅滩相连。",
      "南部陆架缓慢下沉形成浅海，承接大陆主要水系的入海口。",
      18,
      78,
      66,
      20,
    ),
    terrain(
      "北境冠脉",
      "mountain_range",
      0,
      "core",
      "横贯大陆北部的高大山系，连续雪峰构成最醒目的东西向屏障。",
      "大陆北缘挤压隆起形成连续褶皱山系，控制北部通行与水系源头。",
      24,
      18,
      48,
      16,
    ),
    terrain(
      "中央沃原",
      "plain",
      0,
      "major",
      "位于山脉南侧的广阔冲积平原，地势舒缓并由多条支流切割。",
      "山地沉积物长期向南堆积，形成连片低地与宽阔河谷。",
      30,
      40,
      38,
      28,
    ),
    terrain(
      "白河",
      "river",
      0,
      "major",
      "发源于北境冠脉，穿过中央沃原后向南汇入暖海。",
      "高山融水汇集成稳定干流，把北部高地与南部海岸连接起来。",
      48,
      29,
      8,
      55,
    ),
    terrain(
      "西风海岸",
      "coast",
      0,
      "supporting",
      "大陆西缘面向苍海的狭长海岸，海岬、港湾与陡崖交替出现。",
      "海浪侵蚀抬升岩岸并切出深湾，形成大陆与外海的主要接触带。",
      14,
      34,
      12,
      42,
    ),
    terrain(
      "暮潮群岛",
      "archipelago",
      1,
      "supporting",
      "散布在西陲苍海外缘的岛链，与大陆西岸隔着多条潮汐水道。",
      "沉没山脊的高点露出海面，排列成由东北向西南延伸的群岛。",
      3,
      38,
      12,
      24,
    ),
  ],
  relations: [
    relation(3, 4, "borders", "北境冠脉沿中央沃原北缘延伸，构成高地与低地的清晰边界。"),
    relation(5, 4, "crosses", "白河自北向南穿过中央沃原，形成贯穿平原的主水道。"),
    relation(5, 2, "flows_into", "白河在大陆南缘形成河口，并最终汇入南境暖海。"),
    relation(6, 1, "opens_to", "西风海岸的港湾与海峡全部向西陲苍海敞开。"),
  ],
} satisfies NovelXGrowth.Profile

function terrain(
  name: string,
  kind: NovelXGrowth.TerrainKind,
  parentNodeIndex: number | null,
  prominence: "core" | "major" | "supporting",
  summary: string,
  formation: string,
  x: number,
  y: number,
  width: number,
  height: number,
): NovelXGrowth.TerrainNodeProfile {
  return { name, kind, parentNodeIndex, prominence, summary, formation, map: { x, y, width, height } }
}

function relation(
  fromNodeIndex: number,
  toNodeIndex: number,
  kind: NovelXGrowth.TerrainRelationKind,
  summary: string,
): NovelXGrowth.TerrainRelationProfile {
  return { fromNodeIndex, toNodeIndex, kind, summary }
}
